### ISSUE TITLE
Features Research

### ISSUE THREAD

**Issue by davidamunga** [chingu-voyages/v12-bears-team-05#8]
Research on features involved in the recipe app

**Comment by vikneshwar** [comment]
Below are the features we can concentrate:
- [ ] Search and find recipes
- [ ] Add your own recipes and share it (kind of social media for food, we can follow people and like their recipes or comment on them)
- [ ]  Weekly meal planner
- [ ] Show nutrition details for the recipe (calories, proteins, ...)
- [x] Make it a PWA so users upload their bills and we can scan show the recipe based on the available ingredients in the kitchen
